# Cloud Build configuration for clinvar-streams
#
# Command line test usage:
# gcloud builds submit --project=clingen-stage --config ./cloudbuild.yaml \
#  --substitutions=COMMIT_SHA="testbuild" .

# Builds clinvar-streams docker image artifact and pushes it to the project gcr
# Also build a dependencies image, which contains maven and clojars deps
# which can serve as the starting point for a test and source jar build
# as long as /project.clj has not changed.

# Since it pushes the deps image as :latest, if multiple feature branches
# build in the same cloud build project with different project.clj files,
# this may invalidate :latest and negate its caching
steps:
  # Pull latest deps image if one already exists
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull gcr.io/$PROJECT_ID/clinvar-streams-deps:latest || exit 0' ]
  # Build deps image. Will do nothing if deps haven't changed
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '.',
            '-f', 'docker/clinvar-streams.Dockerfile',
            '--target', 'clinvar-streams-deps',
            '-t', 'gcr.io/$PROJECT_ID/clinvar-streams-deps:$COMMIT_SHA',
            '-t', 'gcr.io/$PROJECT_ID/clinvar-streams-deps:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/clinvar-streams-deps:latest' ]

  # build code (we could cache this image as well, by pulling, and pushing at end)
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '.',
            '-f', 'docker/clinvar-streams.Dockerfile',
            '--target', 'builder',
            '-t', 'gcr.io/$PROJECT_ID/clinvar-streams-builder:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/clinvar-streams-deps:latest' ]
  # run tests in code builder image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'run',
            'gcr.io/$PROJECT_ID/clinvar-streams-builder:latest',
            'lein', 'test' ]

  # Build release image, using builder image as cache
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '.',
            '-f', 'docker/clinvar-streams.Dockerfile',
            '-t', 'gcr.io/$PROJECT_ID/clinvar-streams:$COMMIT_SHA',
            '--cache-from', 'gcr.io/$PROJECT_ID/clinvar-streams-builder:latest' ]

# push the images
# The builder image is not pushed, because is will almost certainly
# change any time a file change occurs in the source tree, so it is
# not useful to cache it in the registry.
images:
  - 'gcr.io/$PROJECT_ID/clinvar-streams-deps:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/clinvar-streams-deps:latest'
  - 'gcr.io/$PROJECT_ID/clinvar-streams:$COMMIT_SHA'

# timeout if not complete in 30 minutes
timeout: 1800s
